[package]
name = "day7"
version = "0.1.0"
authors = ["Christian Blades <cblades@pindrop.com>"]
edition = "2018"

[dependencies]
nom = "4.1"
log = "0.4"
env_logger = "0.6"
dot = "0.1"
topological-sort = "0.1"
tap = "0.3"